# Generated by Django 3.0 on 2019-12-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUpload', models.CharField(max_length=200)),
                ('resumoCriptografico', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'resumo',
            },
        ),
    ]
