# Generated by Django 3.0 on 2019-12-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsec', '0002_resumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumo',
            name='arquivo',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
