# Generated by Django 3.0 on 2019-12-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsec', '0003_resumo_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumo',
            name='resumoCriptografico',
            field=models.CharField(max_length=64),
        ),
    ]
