# Generated by Django 3.0 on 2019-12-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsec', '0004_auto_20191208_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(max_length=4)),
                ('n', models.IntegerField(max_length=617)),
                ('e', models.IntegerField(max_length=617)),
                ('p', models.IntegerField(max_length=617)),
                ('q', models.IntegerField(max_length=617)),
                ('d', models.IntegerField(max_length=617)),
            ],
            options={
                'db_table': 'chaves',
            },
        ),
        migrations.AlterField(
            model_name='resumo',
            name='arquivo',
            field=models.FileField(blank=True, default='', upload_to='files'),
        ),
    ]
