# Generated by Django 3.0 on 2019-12-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsec', '0005_auto_20191208_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaves',
            name='d',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chaves',
            name='e',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chaves',
            name='n',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chaves',
            name='p',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chaves',
            name='q',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chaves',
            name='tipo',
            field=models.IntegerField(),
        ),
    ]
