# Generated by Django 3.0 on 2019-12-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsec', '0008_auto_20191208_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificado',
            old_name='serial',
            new_name='serialNumber',
        ),
        migrations.AddField(
            model_name='certificado',
            name='issuer',
            field=models.CharField(default='teste', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='certificado',
            table='certificados',
        ),
    ]
