# Generated by Django 3.0 on 2019-12-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsec', '0009_auto_20191208_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='subject',
        ),
        migrations.AddField(
            model_name='certificado',
            name='CertificateName',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificado',
            name='Organisation',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificado',
            name='OrganisationalUnit',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificado',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificado',
            name='locality',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificado',
            name='state',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
