# Generated by Django 3.0 on 2019-12-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labsec', '0010_auto_20191208_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificado',
            old_name='Organisation',
            new_name='Organization',
        ),
        migrations.RenameField(
            model_name='certificado',
            old_name='OrganisationalUnit',
            new_name='OrganizationalUnit',
        ),
    ]
