# Generated by Django 3.0 on 2019-12-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labsec', '0011_auto_20191208_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificado',
            old_name='city',
            new_name='country',
        ),
    ]
