# Generated by Django 3.0 on 2019-12-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsec', '0012_auto_20191208_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='issuer',
        ),
        migrations.AlterField(
            model_name='certificado',
            name='CertificateName',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='Organization',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='OrganizationalUnit',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='country',
            field=models.CharField(default='BR', max_length=2),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='locality',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='serialNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='state',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
