# Generated by Django 3.0 on 2019-12-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsec', '0013_auto_20191208_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificado',
            old_name='OrganizationalUnit',
            new_name='organizationalUnit',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='CertificateName',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='Organization',
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificateName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='certificado',
            name='organization',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='country',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='locality',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
    ]
