# Generated by Django 3.0 on 2019-12-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labsec', '0014_auto_20191209_0453'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='certificado',
            managers=[
            ],
        ),
    ]
